spotify: updated start script / checks the url before updating & installing the package

diff --git a/packages/5schatten/apps/spotify/scripts/spotify b/packages/5schatten/apps/spotify/scripts/spotify
--- a/packages/5schatten/apps/spotify/scripts/spotify
+++ b/packages/5schatten/apps/spotify/scripts/spotify
@@ -11,56 +11,64 @@ SPOTIFY_CACHE=/storage/.cache/spotify
 SPOTIFY_CONFIG_PATH=/storage/.config/spotify
 SPOTIFY_VERSION=$SPOTIFY_CONFIG_PATH/spotify.version
 SPOTIFY_LOG=/var/log/spotify
-SPOTIFY_BRANCH_SELECT=$SPOTIFY_CONFIG_PATH/stable
 SPOTIFY_BRANCH_DEV=https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=spotify
 SPOTIFY_BRANCH_STABLE=$SPOTIFY_BRANCH_DEV-stable
+RR_ADVANCED_CONF=/storage/.config/rr-config/advanced.conf
+SPOTIFY_BRANCH=$(cat ${RR_ADVANCED_CONF} | grep RR_SPOTIFY_BRANCH= | cut -f2- -d"=")
 
-if [ -f $SPOTIFY_BRANCH_SELECT ]; then
-  SPOTIFY_PKGVER=`curl -s "$SPOTIFY_BRANCH_STABLE" | grep -E '^pkgver=' | cut -c8-17`
+if [ ${SPOTIFY_BRANCH} = "dev" ]; then
+  SPOTIFY_PKGVER=`curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^pkgver=' | cut -c8-17`
   if [ -z "$1" ]; then
-    export `curl -s "$SPOTIFY_BRANCH_STABLE" | grep -E '^pkgver='` || exit 1
-    export `curl -s "$SPOTIFY_BRANCH_STABLE" | grep -E '^_commit='` || exit 1
-    export `curl -s "$SPOTIFY_BRANCH_DEV" | grep -E '^source_x86_64='` || exit 1
-    export `curl -s "$SPOTIFY_BRANCH_STABLE" | grep -E '^_ver_x86_64='`
-    export url=`echo $source_x86_64 | sed s:\$\{pkgver\}:$pkgver: | sed s:\$\{_anotherpkgver\}:.$_commit: | sed s:\$\{_amd64_pkgrel\}:$_ver_x86_64: | cut -d \" -f 2`
-  else
-    export url="$1"
-  fi
-else
-  SPOTIFY_PKGVER=`curl -s "$SPOTIFY_BRANCH_DEV" | grep -E '^pkgver=' | cut -c8-17`
-  if [ -z "$1" ]; then
-    export `curl -s "$SPOTIFY_BRANCH_DEV" | grep -E '^pkgver='` || exit 1
-    export `curl -s "$SPOTIFY_BRANCH_DEV" | grep -E '^_anotherpkgver='` || exit 1
-    export `curl -s "$SPOTIFY_BRANCH_DEV" | grep -E '^source_x86_64='` || exit 1
-    export `curl -s "$SPOTIFY_BRANCH_DEV" | grep -E '^_amd64_pkgrel='`
+    export `curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^pkgver='` || exit 1
+    export `curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^_anotherpkgver='` || exit 1
+    export `curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^source_x86_64='` || exit 1
+    export `curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^_amd64_pkgrel='`
     export url=`echo $source_x86_64 | sed s:\$\{pkgver\}:$pkgver: | sed s:\$\{_anotherpkgver\}:$_anotherpkgver: | sed s:\$\{_amd64_pkgrel\}:$_amd64_pkgrel: | cut -d \" -f 2`
   else
     export url="$1"
   fi 
+else
+  SPOTIFY_PKGVER=`curl -s "${SPOTIFY_BRANCH_STABLE}" | grep -E '^pkgver=' | cut -c8-17`
+  if [ -z "$1" ]; then
+    export `curl -s "${SPOTIFY_BRANCH_STABLE}" | grep -E '^pkgver='` || exit 1
+    export `curl -s "${SPOTIFY_BRANCH_STABLE}" | grep -E '^_commit='` || exit 1
+    export `curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^source_x86_64='` || exit 1
+    export `curl -s "${SPOTIFY_BRANCH_STABLE}" | grep -E '^_ver_x86_64='`
+    export url=`echo $source_x86_64 | sed s:\$\{pkgver\}:$pkgver: | sed s:\$\{_anotherpkgver\}:.$_commit: | sed s:\$\{_amd64_pkgrel\}:$_ver_x86_64: | cut -d \" -f 2`
+  else
+    export url="$1"
+  fi
 fi
+
+SPOTIFY_URL_STATUS=`curl -s --head $url | head -n 1 | grep "HTTP/1.[01] [23].."`
+
+# Clean up
+rm -rf /tmp/spotify
+rm -f ${SPOTIFY_LOG}*.log
 
 install_spotify() {
   kodi-send --action="Notification(Spotify,This is the first time you are starting Spotify. It is being downloaded in the background,13000,${ICON})"
   mkdir -p /tmp/spotify ; cd /tmp/spotify
-  wget -q $url || exit 1
+  wget -q ${url} || exit 1
   kodi-send --action="Notification(Spotify,Download finished. Installing Spotify.,8000,${ICON})"
   ar -x *.deb && tar -zxf data.tar.gz
-  rm -rf $SPOTIFY_CACHE
-  mv usr/share/spotify $SPOTIFY_HOME
-  echo $SPOTIFY_PKGVER > $SPOTIFY_VERSION 2>&1
+  rm -rf ${SPOTIFY_CACHE}
+  mv usr/share/spotify ${SPOTIFY_HOME}
+  echo ${SPOTIFY_PKGVER} > ${SPOTIFY_VERSION} 2>&1
   cd ~ ; rm -rf /tmp/spotify
 }
 
 update_spotify() {
   kodi-send --action="Notification(Spotify,Updating Spotify. It is being downloaded in the background.,8000,${ICON})"
   mkdir -p /tmp/spotify ; cd /tmp/spotify
-  wget -q $url || exit 1
+  wget -q ${url} || exit 1
   kodi-send --action="Notification(Spotify,Download finished. Updating Spotify.,8000,${ICON})"
   ar -x *.deb && tar -zxf data.tar.gz
-  rm -rf $SPOTIFY_HOME
+  rm -rf ${SPOTIFY_HOME}
   rm -rf $SPOTIFY_CACHE
-  mv usr/share/spotify $SPOTIFY_HOME
-  echo $SPOTIFY_PKGVER > $SPOTIFY_VERSION 2>&1
+  rm ${SPOTIFY_VERSION}
+  mv usr/share/spotify ${SPOTIFY_HOME}
+  echo ${SPOTIFY_PKGVER} > ${SPOTIFY_VERSION} 2>&1
   cd ~ ; rm -rf /tmp/spotify
 }
 
@@ -68,21 +76,25 @@ run_spotify() {
   kodifreeze.sh freeze_noPA
   systemctl stop pulseaudio
 
-  $SPOTIFY_HOME/spotify "$@"
+  ${SPOTIFY_HOME}/spotify "$@"
 
   systemctl start pulseaudio
   kodifreeze.sh unfreeze_noPA
 }
 
-if [ ! -x $SPOTIFY_HOME ]; then
-  install_spotify "$1" > $SPOTIFY_LOG-install.log 2>&1
+if [ ! -z "${SPOTIFY_URL_STATUS}" ]; then
+  if [ ! -x ${SPOTIFY_HOME} ]; then
+    install_spotify "$1" > ${SPOTIFY_LOG}-install.log 2>&1
+  fi
+
+  if [ "${SPOTIFY_PKGVER}" != "$(cat ${SPOTIFY_VERSION})" ]; then
+    update_spotify "$1" > ${SPOTIFY_LOG}-update.log 2>&1
+  fi
+elif [ ! -x ${SPOTIFY_HOME} ] && [ -z "${SPOTIFY_URL_STATUS}" ]; then
+  kodi-send --action="Notification(Spotify,Could not find the Spotify package. Set Spotify branch to dev or wait for an updated package url. ,14000,${ICON})" >> ${SPOTIFY_LOG}-install.log 2>&1
 fi
 
-if [ "$SPOTIFY_PKGVER" != "$(cat $SPOTIFY_VERSION)" ]; then
-  update_spotify "$1" > $SPOTIFY_LOG-update.log 2>&1
-fi
-
-if [ -f $SPOTIFY_HOME/spotify ]; then
+if [ -f ${SPOTIFY_HOME}/spotify ]; then
   # Set ALSA output device
   set_ALSA_output_device
 
@@ -92,5 +104,6 @@ if [ -f $SPOTIFY_HOME/spotify ]; then
     usleep 21000000
   fi
 
-  run_spotify "$@" > $SPOTIFY_LOG.log 2>&1
+  run_spotify "$@" > ${SPOTIFY_LOG}.log 2>&1
 fi
+
