spotify: reworked start script

diff --git a/packages/5schatten/apps/spotify/scripts/spotify b/packages/5schatten/apps/spotify/scripts/spotify
--- a/packages/5schatten/apps/spotify/scripts/spotify
+++ b/packages/5schatten/apps/spotify/scripts/spotify
@@ -1,54 +1,63 @@
 #!/bin/sh
 # SPDX-License-Identifier: GPL-2.0-or-later
-# Copyright (C) Originally created by Escalade (https://github.com/escalade)
 # Copyright (C) 2018-present 5schatten (https://github.com/5schatten)
 
 . /etc/profile
 oe_setup_addon service.rr-config-tool
 
+# Set common vars
 ICON=/usr/config/spotify/icon.png
 SPOTIFY_HOME=/storage/.cache/app.spotify
 SPOTIFY_CACHE=/storage/.cache/spotify
 SPOTIFY_CONFIG_PATH=/storage/.config/spotify
 SPOTIFY_VERSION=$SPOTIFY_CONFIG_PATH/spotify.version
 SPOTIFY_LOG=/var/log/spotify
-SPOTIFY_BRANCH_DEV=https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=spotify
-SPOTIFY_BRANCH_STABLE=$SPOTIFY_BRANCH_DEV-stable
+SPOTIFY_BRANCH_STABLE=https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=spotify
+SPOTIFY_BRANCH_DEV=https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=spotify-dev
 
-if [ ${RR_SPOTIFY_BRANCH} = "dev" ]; then
-  SPOTIFY_PKGVER=`curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^pkgver=' | cut -c8-17`
-  if [ -z "$1" ]; then
-    export `curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^pkgver='` || exit 1
-    export `curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^_anotherpkgver='` || exit 1
-    export `curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^source_x86_64='` || exit 1
-    export `curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^_amd64_pkgrel='`
-    export url=`echo $source_x86_64 | sed s:\$\{pkgver\}:$pkgver: | sed s:\$\{_anotherpkgver\}:$_anotherpkgver: | sed s:\$\{_amd64_pkgrel\}:$_amd64_pkgrel: | cut -d \" -f 2`
-  else
-    export url="$1"
-  fi 
-else
-  SPOTIFY_PKGVER=`curl -s "${SPOTIFY_BRANCH_STABLE}" | grep -E '^pkgver=' | cut -c8-17`
-  if [ -z "$1" ]; then
-    export `curl -s "${SPOTIFY_BRANCH_STABLE}" | grep -E '^pkgver='` || exit 1
-    export `curl -s "${SPOTIFY_BRANCH_STABLE}" | grep -E '^_commit='` || exit 1
-    export `curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^source_x86_64='` || exit 1
-    export `curl -s "${SPOTIFY_BRANCH_STABLE}" | grep -E '^_ver_x86_64='`
-    export url=`echo $source_x86_64 | sed s:\$\{pkgver\}:$pkgver: | sed s:\$\{_anotherpkgver\}:.$_commit: | sed s:\$\{_amd64_pkgrel\}:$_ver_x86_64: | cut -d \" -f 2`
-  else
-    export url="$1"
+# Get the current online version
+get_spotify_version() {
+  case ${RR_SPOTIFY_BRANCH} in
+    dev)
+      SPOTIFY_PKGVER=`curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^pkgver=' | cut -f2- -d"="` || exit 1
+      ;;
+    *)
+      SPOTIFY_PKGVER=`curl -s "${SPOTIFY_BRANCH_STABLE}" | grep -E '^pkgver=' | cut -f2- -d"="` || exit 1
+      ;;
+  esac
+  if [ ! -z "${SPOTIFY_PKGVER}" ]; then
+    echo ${SPOTIFY_PKGVER}
   fi
-fi
+}
 
-SPOTIFY_URL_STATUS=`curl -s --head $url | head -n 1 | grep "HTTP/1.[01] [23].."`
+# Retrieve the Spotify download URL depending on the chosen branch
+get_spotify_download_url() {
+  SOURCE_x86_64=`curl -s "${SPOTIFY_BRANCH_STABLE}" | grep -E '^source_x86_64=' | cut -f2- -d":" | cut -f2- -d":" | cut -f1 -d"\""` || exit 1
+  case $1 in
+    dev)
+      PKGVER=`curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^pkgver=' | cut -f2- -d"="` || exit 1
+      COMMIT=`curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^_commit=' | cut -f2- -d"="` || exit 1
+      VER_x86_64=`curl -s "${SPOTIFY_BRANCH_DEV}" | grep -E '^_epoch='| cut -f2- -d"="` || exit 1
+      URL=`echo ${SOURCE_x86_64} | sed s:\$\{pkgver\}:${PKGVER}: | sed s:\$\{_commit\}:${COMMIT}: | sed s:\$\{_ver_x86_64\}:${VER_x86_64}: | cut -d \" -f 2`
+    ;;
+    *)
+      PKGVER=`curl -s "${SPOTIFY_BRANCH_STABLE}" | grep -E '^pkgver=' | cut -f2- -d"="` || exit 1
+      COMMIT=`curl -s "${SPOTIFY_BRANCH_STABLE}" | grep -E '^_commit=' | cut -f2- -d"="` || exit 1
+      VER_x86_64=`curl -s "${SPOTIFY_BRANCH_STABLE}" | grep -E '^_ver_x86_64='| cut -f2- -d"="` || exit 1
+      URL=`echo ${SOURCE_x86_64} | sed s:\$\{pkgver\}:${PKGVER}: | sed s:\$\{_commit\}:${COMMIT}: | sed s:\$\{_ver_x86_64\}:${VER_x86_64}: | cut -d \" -f 2`
+    ;;
+  esac
+  URL_STATUS=`curl -s --head ${URL} | head -n 1 | grep "HTTP/1.[01] [23].."`
+  if [ ! -z "${URL_STATUS}" ]; then
+    echo ${URL}
+  fi
+}
 
-# Clean up
-rm -rf /tmp/spotify
-rm -f ${SPOTIFY_LOG}*.log
-
+# Install Spotify
 install_spotify() {
   kodi-send --action="Notification(Spotify,This is the first time you are starting Spotify. It is being downloaded in the background,13000,${ICON})"
   mkdir -p /tmp/spotify ; cd /tmp/spotify
-  wget -q ${url} || exit 1
+  wget -q ${SPOTIFY_DOWNLOAD_URL} || exit 1
   kodi-send --action="Notification(Spotify,Download finished. Installing Spotify.,8000,${ICON})"
   ar -x *.deb && tar -zxf data.tar.gz
   rm -rf ${SPOTIFY_CACHE}
@@ -57,10 +66,11 @@ install_spotify() {
   cd ~ ; rm -rf /tmp/spotify
 }
 
+# Update Spotify or switch branch
 update_spotify() {
   kodi-send --action="Notification(Spotify,Updating Spotify. It is being downloaded in the background.,8000,${ICON})"
   mkdir -p /tmp/spotify ; cd /tmp/spotify
-  wget -q ${url} || exit 1
+  wget -q ${SPOTIFY_DOWNLOAD_URL} || exit 1
   kodi-send --action="Notification(Spotify,Download finished. Updating Spotify.,8000,${ICON})"
   ar -x *.deb && tar -zxf data.tar.gz
   rm -rf ${SPOTIFY_HOME}
@@ -71,6 +81,7 @@ update_spotify() {
   cd ~ ; rm -rf /tmp/spotify
 }
 
+# Freeze Kodi / Stop PulseAudio / Run Spotify
 run_spotify() {
   kodifreeze.sh freeze_noPA
   systemctl stop pulseaudio
@@ -79,19 +90,34 @@ run_spotify() {
   kodifreeze.sh unfreeze_noPA
 }
 
-if [ ! -z "${SPOTIFY_URL_STATUS}" ]; then
+# Clean up
+rm -rf /tmp/spotify
+rm -f ${SPOTIFY_LOG}*.log
+
+# Get the current download URL & version 
+SPOTIFY_PKGVER=$(get_spotify_version ${RR_SPOTIFY_BRANCH})
+SPOTIFY_DOWNLOAD_URL=$(get_spotify_download_url ${RR_SPOTIFY_BRANCH})
+
+# Install / Update Spotify if necessary
+if [ ! -z "${SPOTIFY_DOWNLOAD_URL}" ]; then
   if [ ! -x ${SPOTIFY_HOME} ]; then
+    echo "Installing Spotify" ${SPOTIFY_PKGVER} "(Branch: "${RR_SPOTIFY_BRANCH}")"
     install_spotify "$1" > ${SPOTIFY_LOG}-install.log 2>&1
   fi
 
-  if [ "${SPOTIFY_PKGVER}" != "$(cat ${SPOTIFY_VERSION})" ]; then
+  # Update if installed version != online version
+  if [ "${SPOTIFY_PKGVER}" != "$(cat ${SPOTIFY_VERSION})" ] && [ ! -z "${SPOTIFY_PKGVER}" ]; then
+    echo "Updating Spotify" "$(cat ${SPOTIFY_VERSION})" "to" "${SPOTIFY_PKGVER}" "(Branch: "${RR_SPOTIFY_BRANCH}")"
     update_spotify "$1" > ${SPOTIFY_LOG}-update.log 2>&1
   fi
-elif [ ! -x ${SPOTIFY_HOME} ] && [ -z "${SPOTIFY_URL_STATUS}" ]; then
-  kodi-send --action="Notification(Spotify,Could not find the Spotify package. Set Spotify branch to dev or wait for an updated package url. ,14000,${ICON})" >> ${SPOTIFY_LOG}-install.log 2>&1
 fi
 
+# Start Spotify if binary is in place
 if [ -f ${SPOTIFY_HOME}/spotify ]; then
+  echo "Starting Spotify" "$(cat ${SPOTIFY_VERSION})" "(Branch: "${RR_SPOTIFY_BRANCH}")"
   run_spotify "$@" > ${SPOTIFY_LOG}.log 2>&1
-fi
 
+# If download URL is invalid & no Spotify binary is found send error message
+elif [ ! -f ${SPOTIFY_HOME}/spotify ] && [ -z "${SPOTIFY_DOWNLOAD_URL}" ]; then
+  kodi-send --action="Notification(Spotify,Could not download the Spotify package. Try to set the Spotify branch to dev or wait for a package update. ,15500,${ICON})" >> ${SPOTIFY_LOG}-install.log 2>&1
+fi
